### ISSUE TITLE
强制要求jdk版本1.7

### ISSUE THREAD

**Issue by perfmeta** [DoctorQ/CrashMonkey4Android#1]
jdk1.8都不支持

**Comment by DoctorQ** [comment]
贴一下出错的信息，谢谢

**Comment by DoctorQ** [comment]
在cts-tradefed脚本中，将第38行`JAVA_VERSION=$(java -version 2>&1 | head -n 1 | grep '[ "]1\.7[\. "$$]')` 修改为`JAVA_VERSION=$(java -version 2>&1 | head -n 1 | grep '[ "]1\.[78][\. "$$]')`

**Comment by DoctorQ** [comment]
已修复运行脚本38行修改为如下：`JAVA_VERSION=$(java -version 2>&1 | head -n 1 | grep '[ "]1\.[678][\. "$$]')`

**Comment by DoctorQ** [comment]
dd
