### ISSUE TITLE
能否测试一个应用程序下面不同包名下的monkey

### ISSUE THREAD

**Issue by killuwaxkilluwa** [DoctorQ/CrashMonkey4Android#3]
您好，我看了您的monkey，首先需要输入应用程序包名，然后需要输入activey名，想问下，可不可以输入应用程序下某个模块的包名，然后monkey只跑这个模块下的功能呢？

**Comment by DoctorQ** [comment]
不可以，模块的包名对于android系统来说都是不可见的，系统也只认识android的包名。

**Comment by DoctorQ** [comment]
@killuwaxkilluwa 不可以，对于android系统来说，只识别应用的包名，不识别模块。
